---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

#- include: centos.yml
# when: ansible_distribution == 'CentOS'

- import_tasks: user.yml
- import_tasks: cif.yml

- import_tasks: smrt/main.yml
  when: cif_smrt_enabled

- import_tasks: router/main.yml
  when: cif_router_enabled